feat(docker): dockerize app to be deployed
EPFL-ENAC/LASUR-swiss-proximity pull request #31
Opened 2022-12-10 21:59 UTC by pierreleripoll

# Describe your changes

I copied Alicelanding structure for docker configuration, actually running `make deploy` does run the app with docker. I think everything needed for the app to be hosted on EPFL's server is set.

# Related GitHub issues and pull requests

- Ref: close #30

2022-12-12 07:50 UTC, blueur requested changes

2022-12-12 07:50 UTC, blueur commented on frontend/Dockerfile-apache
> +RUN wget https://tequila.epfl.ch/download/2.0/tequila-apache-C-2.0.17.tgz -O tequila-apache.tgz && \
Tu n'as pas besoin de tequila, donc pas besoin de ce fichier, tu n'auras que nginx

2022-12-12 07:50 UTC, blueur commented on README.md
> +See `/data_processing/README.md`
Il y a un data processing ?

2022-12-13 09:27 UTC, pierreleripoll commented
> @pierreleripoll : Préfère des rebase au lieu de merge depuis main

Ok, même pour merge un feature dans la branche develop je fais plutôt des rebase ?

2022-12-13 09:29 UTC, merged

2022-12-13 11:38 UTC, blueur commented
Je suis partisant du rebase partout ^^