Feat/real data martin
EPFL-ENAC/LASUR-swiss-proximity pull request #55
Opened 2023-10-14 12:23 UTC by pierreleripoll

# Describe your changes

Real dataset needed changes in data viewing (properties, access etc) + changes in app UI, new legend feature, variables are selected differently according if demand or supply
See #53 for app mock up reference

# Related GitHub issues and pull requests

- Closes #53 #52 #51 #37

2023-10-16 12:43 UTC, ymarcon requested changes
Tested, works very well, except some minor comments (+ favicon is vuetify's one); also you should run `npm audit fix`.

2023-10-16 12:43 UTC, ymarcon commented on frontend/src/components/InfoMarkdown.md
> +### Proximity criteria formula
La webapp est en FR ou EN ? il me semble qu'il faudrait choisir.

2023-10-16 12:43 UTC, ymarcon commented on frontend/src/components/InfoDialog.vue
> +::v-deep.markdown-body p {
There is a warning:

```
[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.
```

See https://stackoverflow.com/questions/63986278/vue-3-v-deep-usage-as-a-combinator-has-been-deprecated-use-v-deepinner-se

2023-10-16 20:46 UTC, pierreleripoll commented on frontend/src/components/InfoMarkdown.md
> +### Proximity criteria formula
done

2023-10-16 20:47 UTC, pierreleripoll commented
@ymarcon  thanks for feedback ! I modified the app according to them, let me know if this is ok for you

2023-10-17 07:31 UTC, ymarcon approved these changes
LGBT :+1:

2023-10-17 07:45 UTC, merged